{{- with $.Values }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eks-connector.fullname" $ }}-secret-access
subjects:
  - kind: ServiceAccount
    name: {{ include "eks-connector.serviceAccountName" $ }}
roleRef:
  kind: Role
  name: {{ include "eks-connector.fullname" $ }}-secret-access
  apiGroup: rbac.authorization.k8s.io
{{- end }}
