{{- with $.Values }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eks-connector.fullname" $ }}-activation-config
type: Opaque
data:
  {{- if .eks.activationCode }}
  code: {{ .eks.activationCode }}
  {{- else }}
  {{- fail "eks.activationCode must be set."}}
  {{- end }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "eks-connector.serviceAccountName" $ }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "eks-connector.serviceAccountName" $ }}
{{- end }}
